### PR TITLE
[lang] Oxydates (Adds Rust)

### PR DESCRIPTION
**Pull request by Ocramoi**
### **Description**

Adds `rust.md` to the lang folder, describing the Rust language as per the contribution manual on README.md.

This PR fixes the glaring lack of Rustic representation.

- [ ] Yes, I am a Member of **DEVSTRONS'**

**ocramoi#4456**

### CODE REVIEW

**Review by ghulamyazdani — APPROVED** [review]
LGTM , @amino19 will the emojis before the headings impact our UI of the website?

**Comment by amino19** [comment]
> LGTM , @amino19 will the emojis before the headings impact our UI of the website?

Yes, it's always a good idea to attach emojis at the heading part. It will definitely impact awesome, & readers would like to read more interestingly.

@felixfaisal: I really apologise, I can't wait for your pull request towards specific lang., meanwhile if you wanna add your reviews here, it would be awesome! :raised_hands:

**Comment by felixfaisal** [comment]
Looks great, Everything is fine :D It would be great if you could add somewhere that Rust has grown beyond being a systems language and is being adopted for various things because of the underlying security in memory management. Also will be nice to see 2-3 sentences about the tooling around rust such as cargo, rustfmt etc which makes Rust way better and a link to Rust Foundation Discord server where you can almost ask any query.

**Comment by amino19** [comment]
@felixfaisal: Thanks for your valuable insights, pl feel free to review the changes again as it's updated with your suggestions now. :slightly_smiling_face:

**Review by Panquesito7 — APPROVED** [review]

**Review by felixfaisal — APPROVED** [review]

**Pull request merged**
